name: Run tests

on:
  workflow_dispatch:

jobs:
  jest:
    runs-on: [ 'ubuntu-latest' ]
    steps:
      - uses: actions/checkout@v4
      - name: Install modules
        run: yarn
      - name: Run tests
        run: yarn test

