name: Test `trigger-github-workflow` action
on:
  push:
    branches:
      - main

permissions:
  actions: write

jobs:
  test-trigger-github-workflow:
    runs-on: [ 'ubuntu-latest' ]
    name: Test
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Test
        id: test
        uses: ./
        with:
          repository: yakubique/trigger-github-workflow 
          workflow: ci.yaml
